### ISSUE TITLE
I made some modifications

### ISSUE THREAD

**Issue by pangard** [wzchen/probability_cheatsheet#16]
Hello:
Thanks a lot for publishing the source code. This allows each person to custom to their needs. Indeed, I was only looking for a distribution table, but in the end I handed almost everything else. I had to remove sutff that we do not cover, but also added other stuff that I consider important, or useful, and you may want to add too. I also removed references to R, but included references to python's scipy.stats.
I don't think a pull request is appropriate, since you won't like most of my changes. Is it fine if I just drop my source file here, and you grab whatever you like?

**Comment by pangard** [comment]
I had to upload the source file as txt file (please don't tell github!):

[oye_cheatsheet.txt](https://github.com/wzchen/probability_cheatsheet/files/2996331/oye_cheatsheet.txt)

**Comment by wzchen** [comment]
Thanks for making this! I'm going to close this for now since it's not an open issue, but also feel free to make a fork of this repo.

**Comment by pangard** [comment]
Hi, wzchen:

Yeah, I'll consider forking in the future. For the moment, please look at this other updated version:

[oye_cheatsheet.pdf](https://github.com/wzchen/probability_cheatsheet/files/3344440/oye_cheatsheet.pdf)
[oye_cheatsheet.txt](https://github.com/wzchen/probability_cheatsheet/files/3344441/oye_cheatsheet.txt)

Have a nice day
