### ISSUE TITLE
Repeat definitions of PMF and CDF

### ISSUE THREAD

**Issue by e5c** [wzchen/probability_cheatsheet#3]
Hi there,
You define the PMF and CDF in each of these two consecutive sections: "Random Variables and their Distributions" and "Expected Value and Indicators" on page 1. It seems like it would suffice to place these only in the former section. Is this intentional? 

Cheers,
Eliza

**Comment by wzchen** [comment]
Thanks for reporting this (and sorry for the delay in response) - this has been fixed in Version 2.0!
